output_dir: "models/ablation/"
seed: 42
resume_from_checkpoint: "latest"

batch_size: 32 # 200 for ReCamMaster
num_train_epochs: 2
max_train_steps: 20000 # 80000
guidance_scale: 2.0
conditioning_dropout_prob: 0.1 # 0.25 previous try 0.1
checkpointing_steps: 5000
checkpoints_total_limit: 3
logging_dir: "logs/ablation"
allow_tf32: false
report_to: "wandb"
mixed_precision: null
enable_xformers_memory_efficient_attention: True
use_gradient_checkpointing: True
use_gradient_checkpointing_offload: True
set_grads_to_none: True
gradient_accumulation_steps: 1 # need to  1 if using 8 GPU
gradient_checkpointing: True
learning_rate: 0.0001 # 0.0001
scale_lr: false
lr_scheduler: "cosine" #"constant_with_warmup"
lr_warmup_steps: 0
lr_num_cycles: 1
lr_power: 1.0
use_8bit_adam: True
dataloader_num_workers: 4
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1e-08
push_to_hub: false
hub_token: null
hub_model_id: null

dataset_path: "./laval-objaverse-dataset"
wan_path: "./models/Wan-AI/Wan2.1-T2V-1.3B"
max_grad_norm: 0.1 # vanilla 0.1

tiled: False
mini_validation_steps: 2000
validation_steps: 5000 # When to go to log_validation
tracker_project_name: "RelightFormer"

# model
rope: "PRoPE" # wan wan-no-frame prope gta cape so4
resolution: 256

# ablation
ablation: True
training_in_same_view: True
max_view: 16
channel: False
